### ISSUE TITLE
[learning LXD] Prefer snap package over PPA

### ISSUE THREAD

**Issue by sparkiegeek** [nottrobin/development.robinwinslow.uk#1]
https://linuxcontainers.org/lxd/getting-started-cli/#snap-package-archlinux-debian-fedora-opensuse-and-ubuntu

The snap package is a cross-platform solution for getting latest LXD.

For support on earlier series, you should probably just link out to https://linuxcontainers.org/lxd/getting-started-cli/#installation ?

**Comment by nottrobin** [comment]
Yeah you're right maybe I should just remove that section. It's 'cos I originally wrote the article when I was running Trusty and (I think) before the LXD snap existed.
