### ISSUE TITLE
[learning LXD] Better way of sharing directories

### ISSUE THREAD

**Issue by sparkiegeek** [nottrobin/development.robinwinslow.uk#2]
The fundamental issue with sharing directories is having the kernel know that you're really the same user.

The preferred, and easy way to do this is to setup a mapping of userids from the host to the container.

```
$ lxc launch ubuntu:bionic example-container-c raw.idmap="both $UID 1000"
...
$ lxc config device add example-container example-share disk source="/path/to/directory/to/share" path=/home/ubuntu/whatever
```

**Comment by nottrobin** [comment]
@sparkiegeek sorry, did you say that this actually won't work in a default LXD install?

**Comment by sparkiegeek** [comment]
@nottrobin yes, sorry got distracted.

https://blog.ubuntu.com/2016/12/08/mounting-your-home-directory-in-lxd

covers the changes needed to `/etc/subuid` and `/etc/subgid`
